# 1. FE (Frontend) Service
apiVersion: v1
kind: Service
metadata:
  name: starrocks-fe-service
spec:
  ports:
    - name: mysql-port
      port: 9030
      targetPort: 9030
    - name: http-port
      port: 8030
      targetPort: 8030
    - name: rpc-port
      port: 9010
      targetPort: 9010
  selector:
    app: starrocks-fe
---
# 2. FE StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: starrocks-fe
spec:
  serviceName: starrocks-fe-service
  replicas: 1
  selector:
    matchLabels:
      app: starrocks-fe
  template:
    metadata:
      labels:
        app: starrocks-fe
    spec:
      containers:
        - name: fe
          image: starrocks/fe-ubuntu:latest
          imagePullPolicy: IfNotPresent  # 禁止从远程拉取
          command: ["sleep"]
          args: ["infinity"]
          ports:
            - containerPort: 9030  # MySQL 协议
            - containerPort: 8030  # Web UI
            - containerPort: 9010  # 节点间通信
          env:
            - name: FE_SERVERS
              value: "fe1=starrocks-fe-0.starrocks-fe-service:9010"
          volumeMounts:
            - name: fe-meta
              mountPath: /opt/starrocks/fe/meta
  volumeClaimTemplates:
    - metadata:
        name: fe-meta
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
---
# 3. BE (Backend) Service
apiVersion: v1
kind: Service
metadata:
  name: starrocks-be-service
spec:
  clusterIP: None  # Headless Service
  ports:
    - name: thrift-rpc
      port: 9060
      targetPort: 9060
    - name: web-ui
      port: 8040
      targetPort: 8040
    - name: brpc
      port: 9050
      targetPort: 9050
  selector:
    app: starrocks-be
---
# 4. BE StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: starrocks-be
spec:
  serviceName: starrocks-be-service
  replicas: 1
  selector:
    matchLabels:
      app: starrocks-be
  template:
    metadata:
      labels:
        app: starrocks-be
    spec:
      containers:
        - name: be
          image: starrocks/be-ubuntu:latest
          imagePullPolicy: IfNotPresent  # 禁止从远程拉取
          ports:
            - containerPort: 9060  # Thrift RPC
            - containerPort: 8040  # Web UI
            - containerPort: 9050  # BRPC 通信
          volumeMounts:
            - name: be-data
              mountPath: /opt/starrocks/be/storage
  volumeClaimTemplates:
    - metadata:
        name: be-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
        storageClassName: standard
