apiVersion: v1
kind: Namespace
metadata:
  name: redis

---
# Redis Master StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
  namespace: redis
spec:
  serviceName: redis-master
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis
        image: docker.io/library/redis:7.2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-config
          mountPath: /usr/local/etc/redis
        - name: redis-data
          mountPath: /data
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
      volumes:
      - name: redis-config
        configMap:
          name: redis-master-config
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
# Redis Master ConfigMap (保持不变)
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-master-config
  namespace: redis
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    appendonly yes
    requirepass 123456
    user root on >123456 ~* +@all

---
# Redis Master Service (改为Headless Service)
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master

---
# Redis Slave 1 StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-slave1
  namespace: redis
spec:
  serviceName: redis-slave1
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: slave1
  template:
    metadata:
      labels:
        app: redis
        role: slave1
    spec:
      containers:
      - name: redis
        image: docker.io/library/redis:7.2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-config
          mountPath: /usr/local/etc/redis
        - name: redis-data
          mountPath: /data
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
      volumes:
      - name: redis-config
        configMap:
          name: redis-slave1-config
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
# Redis Slave 1 ConfigMap (保持不变)
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-slave1-config
  namespace: redis
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    appendonly yes
    replicaof redis-master 6379
    masterauth 123456
    requirepass 123456
    user root on >123456 ~* +@all

---
# Redis Slave 1 Service (Headless)
apiVersion: v1
kind: Service
metadata:
  name: redis-slave1
  namespace: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: slave1

---
# Redis Slave 2 StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-slave2
  namespace: redis
spec:
  serviceName: redis-slave2
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: slave2
  template:
    metadata:
      labels:
        app: redis
        role: slave2
    spec:
      containers:
      - name: redis
        image: docker.io/library/redis:7.2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-config
          mountPath: /usr/local/etc/redis
        - name: redis-data
          mountPath: /data
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
      volumes:
      - name: redis-config
        configMap:
          name: redis-slave2-config
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
# Redis Slave 2 ConfigMap (保持不变)
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-slave2-config
  namespace: redis
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    appendonly yes
    replicaof redis-master 6379
    masterauth 123456
    requirepass 123456
    user root on >123456 ~* +@all

---
# Redis Slave 2 Service (Headless)
apiVersion: v1
kind: Service
metadata:
  name: redis-slave2
  namespace: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: slave2

---
# Redis Sentinel 1 StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel1
  namespace: redis
spec:
  serviceName: redis-sentinel1
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: sentinel1
  template:
    metadata:
      labels:
        app: redis
        role: sentinel1
    spec:
      containers:
      - name: sentinel
        image: docker.io/library/redis:7.2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 26379
        volumeMounts:
        - name: sentinel-config
          mountPath: /usr/local/etc/redis
        - name: sentinel-data
          mountPath: /data
        command: ["redis-server", "/usr/local/etc/redis/sentinel.conf", "--sentinel"]
      volumes:
      - name: sentinel-config
        configMap:
          name: redis-sentinel1-config
  volumeClaimTemplates:
  - metadata:
      name: sentinel-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
# Sentinel 1 ConfigMap (添加announce配置)
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel1-config
  namespace: redis
data:
  sentinel.conf: |
    port 26379
    dir /data
    sentinel monitor redis-master redis-master 6379 2
    sentinel down-after-milliseconds redis-master 5000
    sentinel failover-timeout redis-master 10000
    sentinel parallel-syncs redis-master 1
    sentinel resolve-hostnames yes
    sentinel auth-pass redis-master 123456
    sentinel announce-ip redis-sentinel1.redis-sentinel1.redis.svc.cluster.local
    sentinel announce-port 26379

---
# Sentinel 1 Service (Headless)
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel1
  namespace: redis
spec:
  clusterIP: None
  ports:
  - port: 26379
    targetPort: 26379
  selector:
    app: redis
    role: sentinel1

---
# Redis Sentinel 2 StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel2
  namespace: redis
spec:
  serviceName: redis-sentinel2
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: sentinel2
  template:
    metadata:
      labels:
        app: redis
        role: sentinel2
    spec:
      containers:
      - name: sentinel
        image: docker.io/library/redis:7.2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 26379
        volumeMounts:
        - name: sentinel-config
          mountPath: /usr/local/etc/redis
        - name: sentinel-data
          mountPath: /data
        command: ["redis-server", "/usr/local/etc/redis/sentinel.conf", "--sentinel"]
      volumes:
      - name: sentinel-config
        configMap:
          name: redis-sentinel2-config
  volumeClaimTemplates:
  - metadata:
      name: sentinel-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
# Sentinel 2 ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel2-config
  namespace: redis
data:
  sentinel.conf: |
    port 26379
    dir /data
    sentinel monitor redis-master redis-master 6379 2
    sentinel down-after-milliseconds redis-master 5000
    sentinel failover-timeout redis-master 10000
    sentinel parallel-syncs redis-master 1
    sentinel resolve-hostnames yes
    sentinel auth-pass redis-master 123456
    sentinel announce-ip redis-sentinel2.redis-sentinel2.redis.svc.cluster.local
    sentinel announce-port 26379

---
# Sentinel 2 Service
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel2
  namespace: redis
spec:
  clusterIP: None
  ports:
  - port: 26379
    targetPort: 26379
  selector:
    app: redis
    role: sentinel2

---
# Redis Sentinel 3 StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel3
  namespace: redis
spec:
  serviceName: redis-sentinel3
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: sentinel3
  template:
    metadata:
      labels:
        app: redis
        role: sentinel3
    spec:
      containers:
      - name: sentinel
        image: docker.io/library/redis:7.2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 26379
        volumeMounts:
        - name: sentinel-config
          mountPath: /usr/local/etc/redis
        - name: sentinel-data
          mountPath: /data
        command: ["redis-server", "/usr/local/etc/redis/sentinel.conf", "--sentinel"]
      volumes:
      - name: sentinel-config
        configMap:
          name: redis-sentinel3-config
  volumeClaimTemplates:
  - metadata:
      name: sentinel-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
# Sentinel 3 ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel3-config
  namespace: redis
data:
  sentinel.conf: |
    port 26379
    dir /data
    sentinel monitor redis-master redis-master 6379 2
    sentinel down-after-milliseconds redis-master 5000
    sentinel failover-timeout redis-master 10000
    sentinel parallel-syncs redis-master 1
    sentinel resolve-hostnames yes
    sentinel auth-pass redis-master 123456
    sentinel announce-ip redis-sentinel3.redis-sentinel3.redis.svc.cluster.local
    sentinel announce-port 26379

---
# Sentinel 3 Service
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel3
  namespace: redis
spec:
  clusterIP: None
  ports:
  - port: 26379
    targetPort: 26379
  selector:
    app: redis
    role: sentinel3