apiVersion: v1
kind: Namespace
metadata:
  name: starrocks
---
# 1. FE Service
apiVersion: v1
kind: Service
metadata:
  name: starrocks-fe-service
  namespace: starrocks
spec:
  ports:
    - name: mysql-port
      port: 9030
      targetPort: 9030
    - name: http-port
      port: 8030
      targetPort: 8030
    - name: rpc-port
      port: 9010
      targetPort: 9010
  selector:
    app: starrocks-fe
---
# 2. FE StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: starrocks-fe
  namespace: starrocks
spec:
  serviceName: starrocks-fe-service
  replicas: 1
  selector:
    matchLabels:
      app: starrocks-fe
  template:
    metadata:
      labels:
        app: starrocks-fe
    spec:
      containers:
        - name: fe
          image: starrocks/fe-ubuntu:3.3.14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9030  # MySQL port
            - containerPort: 8030  # HTTP port
            - containerPort: 9010  # RPC port
          env:
            - name: FE_SERVERS
              value: "fe1=starrocks-fe-0.starrocks-fe-service:9010"
            - name: FE_ID
              value: "1"
            - name: FE_ROLE
              value: "leader"
          volumeMounts:
            - name: fe-meta
              mountPath: /opt/starrocks/fe/meta
  volumeClaimTemplates:
    - metadata:
        name: fe-meta
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path
---
# 3. BE Service
apiVersion: v1
kind: Service
metadata:
  name: starrocks-be-service
  namespace: starrocks
spec:
  clusterIP: None  # Headless service
  ports:
    - name: be-port
      port: 9060
      targetPort: 9060
  selector:
    app: starrocks-be
---
# 4. BE StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: starrocks-be
  namespace: starrocks
spec:
  serviceName: starrocks-be-service
  replicas: 1
  selector:
    matchLabels:
      app: starrocks-be
  template:
    metadata:
      labels:
        app: starrocks-be
    spec:
      containers:
        - name: be
          image: starrocks/be-ubuntu:3.3.14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9060
          env:
            - name: FE_SERVERS
              value: "starrocks-fe-0.starrocks-fe-service:9010"
          volumeMounts:
            - name: be-data
              mountPath: /opt/starrocks/be/storage
  volumeClaimTemplates:
    - metadata:
        name: be-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path
---
# 5. FE PVC（备用，可提前创建）
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fe-meta-pvc
  namespace: starrocks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
# 6. BE PVC（备用，可提前创建）
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: be-data-pvc
  namespace: starrocks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
